// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oee.Persistence;

#nullable disable

namespace Oee.Persistence.Migrations
{
    [DbContext(typeof(OeeDbContext))]
    partial class OeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oee.Domain.Entities.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.HasKey("Id")
                        .HasName("pk_lines");

                    b.HasIndex("PlantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_lines_plant_id_code");

                    b.ToTable("lines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LINE-A",
                            Name = "Housing Assembly",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "LINE-B",
                            Name = "Bracket Fabrication",
                            PlantId = 1
                        });
                });

            modelBuilder.Entity("Oee.Domain.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<bool>("IsBottleneck")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bottleneck");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SequenceInLine")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_in_line");

                    b.HasKey("Id")
                        .HasName("pk_machines");

                    b.HasIndex("LineId")
                        .IsUnique()
                        .HasDatabaseName("ux_machines_one_bottleneck_per_line")
                        .HasFilter("is_bottleneck");

                    b.HasIndex("LineId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_machines_line_id_code");

                    b.HasIndex("LineId", "SequenceInLine")
                        .HasDatabaseName("ix_machines_line_id_sequence_in_line");

                    b.ToTable("machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "M-A1",
                            IsBottleneck = false,
                            LineId = 1,
                            Name = "Injection Moulder",
                            SequenceInLine = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "M-A2",
                            IsBottleneck = true,
                            LineId = 1,
                            Name = "Assembly Station",
                            SequenceInLine = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "M-A3",
                            IsBottleneck = false,
                            LineId = 1,
                            Name = "Carton Packer",
                            SequenceInLine = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "M-B1",
                            IsBottleneck = false,
                            LineId = 2,
                            Name = "CNC Mill",
                            SequenceInLine = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "M-B2",
                            IsBottleneck = true,
                            LineId = 2,
                            Name = "Robot Welder",
                            SequenceInLine = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "M-B3",
                            IsBottleneck = false,
                            LineId = 2,
                            Name = "Powder Coating Booth",
                            SequenceInLine = 3
                        });
                });

            modelBuilder.Entity("Oee.Domain.Entities.PlannedDowntime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer")
                        .HasColumnName("machine_id");

                    b.Property<int>("ReasonCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("reason_code_id");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    b.Property<TimeOnly>("StartLocal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_local");

                    b.HasKey("Id")
                        .HasName("pk_planned_downtimes");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("ix_planned_downtimes_machine_id");

                    b.HasIndex("ReasonCodeId")
                        .HasDatabaseName("ix_planned_downtimes_reason_code_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_planned_downtimes_shift_id");

                    b.ToTable("planned_downtimes", t =>
                        {
                            t.HasCheckConstraint("ck_planned_downtimes_duration_positive", "duration > interval '0'");

                            t.HasCheckConstraint("ck_planned_downtimes_effective_window_ordered", "effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Days = 31,
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            ReasonCodeId = 1,
                            ShiftId = 1,
                            StartLocal = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Days = 31,
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            ReasonCodeId = 1,
                            ShiftId = 2,
                            StartLocal = new TimeOnly(18, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Days = 31,
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            ReasonCodeId = 1,
                            ShiftId = 3,
                            StartLocal = new TimeOnly(2, 0, 0)
                        });
                });

            modelBuilder.Entity("Oee.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_plants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_plants_code");

                    b.ToTable("plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IST-01",
                            Name = "Istanbul Plant",
                            TimeZoneId = "Europe/Istanbul"
                        });
                });

            modelBuilder.Entity("Oee.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<double>("IdealCycleTimeSec")
                        .HasColumnType("double precision")
                        .HasColumnName("ideal_cycle_time_sec");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_products_code");

                    b.ToTable("products", t =>
                        {
                            t.HasCheckConstraint("ck_products_ideal_cycle_time_positive", "ideal_cycle_time_sec > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PRD-100",
                            IdealCycleTimeSec = 1.0,
                            Name = "Standard Housing"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PRD-200",
                            IdealCycleTimeSec = 1.5,
                            Name = "Reinforced Housing"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PRD-300",
                            IdealCycleTimeSec = 0.75,
                            Name = "Compact Bracket"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PRD-400",
                            IdealCycleTimeSec = 2.5,
                            Name = "Heavy-Duty Bracket"
                        });
                });

            modelBuilder.Entity("Oee.Domain.Entities.ReasonCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_planned");

                    b.Property<int?>("SixBigLossCategory")
                        .HasColumnType("integer")
                        .HasColumnName("six_big_loss_category");

                    b.HasKey("Id")
                        .HasName("pk_reason_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_reason_codes_code");

                    b.ToTable("reason_codes", t =>
                        {
                            t.HasCheckConstraint("ck_reason_codes_category_matches_planned_flag", "(is_planned AND six_big_loss_category IS NULL)\n              OR (NOT is_planned AND six_big_loss_category IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BRK",
                            Description = "Scheduled operator break",
                            IsPlanned = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "PM",
                            Description = "Planned preventive maintenance",
                            IsPlanned = true
                        },
                        new
                        {
                            Id = 3,
                            Code = "NO-DEMAND",
                            Description = "No production scheduled",
                            IsPlanned = true
                        },
                        new
                        {
                            Id = 4,
                            Code = "MECH",
                            Description = "Mechanical failure",
                            IsPlanned = false,
                            SixBigLossCategory = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "ELEC",
                            Description = "Electrical or control failure",
                            IsPlanned = false,
                            SixBigLossCategory = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "CO",
                            Description = "Product changeover",
                            IsPlanned = false,
                            SixBigLossCategory = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "TOOL",
                            Description = "Tool or die change",
                            IsPlanned = false,
                            SixBigLossCategory = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "STARVE",
                            Description = "Starved of material",
                            IsPlanned = false,
                            SixBigLossCategory = 3
                        },
                        new
                        {
                            Id = 9,
                            Code = "BLOCK",
                            Description = "Blocked by downstream station",
                            IsPlanned = false,
                            SixBigLossCategory = 3
                        },
                        new
                        {
                            Id = 10,
                            Code = "SPEED",
                            Description = "Running below rated speed",
                            IsPlanned = false,
                            SixBigLossCategory = 4
                        },
                        new
                        {
                            Id = 11,
                            Code = "DEFECT",
                            Description = "In-process quality defect",
                            IsPlanned = false,
                            SixBigLossCategory = 5
                        },
                        new
                        {
                            Id = 12,
                            Code = "STARTUP",
                            Description = "Scrap produced before process stabilised",
                            IsPlanned = false,
                            SixBigLossCategory = 6
                        });
                });

            modelBuilder.Entity("Oee.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartLocal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_local");

                    b.HasKey("Id")
                        .HasName("pk_shifts");

                    b.HasIndex("LineId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_shifts_line_id_code");

                    b.ToTable("shifts", t =>
                        {
                            t.HasCheckConstraint("ck_shifts_duration_under_a_day", "duration > interval '0' AND duration < interval '24 hours'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A",
                            Days = 31,
                            Duration = new TimeSpan(0, 8, 0, 0, 0),
                            LineId = 1,
                            Name = "Morning",
                            StartLocal = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Code = "B",
                            Days = 31,
                            Duration = new TimeSpan(0, 8, 0, 0, 0),
                            LineId = 1,
                            Name = "Afternoon",
                            StartLocal = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Code = "C",
                            Days = 31,
                            Duration = new TimeSpan(0, 8, 0, 0, 0),
                            LineId = 1,
                            Name = "Night",
                            StartLocal = new TimeOnly(22, 0, 0)
                        });
                });

            modelBuilder.Entity("Oee.Domain.Entities.Line", b =>
                {
                    b.HasOne("Oee.Domain.Entities.Plant", "Plant")
                        .WithMany("Lines")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lines_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Oee.Domain.Entities.Machine", b =>
                {
                    b.HasOne("Oee.Domain.Entities.Line", "Line")
                        .WithMany("Machines")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_machines_lines_line_id");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Oee.Domain.Entities.PlannedDowntime", b =>
                {
                    b.HasOne("Oee.Domain.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_planned_downtimes_machines_machine_id");

                    b.HasOne("Oee.Domain.Entities.ReasonCode", "ReasonCode")
                        .WithMany()
                        .HasForeignKey("ReasonCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_planned_downtimes_reason_codes_reason_code_id");

                    b.HasOne("Oee.Domain.Entities.Shift", "Shift")
                        .WithMany("PlannedDowntimes")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_downtimes_shifts_shift_id");

                    b.Navigation("Machine");

                    b.Navigation("ReasonCode");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Oee.Domain.Entities.Shift", b =>
                {
                    b.HasOne("Oee.Domain.Entities.Line", "Line")
                        .WithMany("Shifts")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_lines_line_id");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Oee.Domain.Entities.Line", b =>
                {
                    b.Navigation("Machines");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Oee.Domain.Entities.Plant", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Oee.Domain.Entities.Shift", b =>
                {
                    b.Navigation("PlannedDowntimes");
                });
#pragma warning restore 612, 618
        }
    }
}
